### ISSUE TITLE
wit unreal don't compile on android ....  

### ISSUE THREAD

**Issue by surfufu** [wit-ai/wit-unreal#50]
Hi, 

We got this error : error: no member named 'BindLambda' in 'TMulticastDelegate<void (const TArray<FString, TSizedDefaultAllocator<32> > &, const TArray<bool, TSizedDefaultAllocator<32> > &), FDefaultDelegateUserPolicy>'; did you mean 'AddLambda'?  in \Plugins\Wit\Source\Wit\Private\Voice\Capture\VoiceCaptureSubsystem.cpp line 77 

We are using UE5, what to do ? 

Regards, 

Nicolas.

**Comment by wangpingsx** [comment]
> Hi,
> 
> We got this error : error: no member named 'BindLambda' in 'TMulticastDelegate<void (const TArray<FString, TSizedDefaultAllocator<32> > &, const TArray<bool, TSizedDefaultAllocator<32> > &), FDefaultDelegateUserPolicy>'; did you mean 'AddLambda'? in \Plugins\Wit\Source\Wit\Private\Voice\Capture\VoiceCaptureSubsystem.cpp line 77
> 
> We are using UE5, what to do ?
> 
> Regards,
> 
> Nicolas.

Hi @surfufu 

Thanks for reporting this. I will help you to solve the issue.

I have tested the latest code with UE5.0 (5.0.3), I can compile it with no problems.  If you are using UE5.0 could you please try again with the latest code from the main branch? If you still see issues, please provide more information on versions and the way to reproduce it.

If you are using UE5.1, bear us for a couple of days, there are some API changes from 5.1, we need to change our code to fit those changes.

thanks

**Comment by wangpingsx** [comment]
> was UE5.0.3 .... strange, maybe the version of android SDK ? I will try again

Android SDK?  Could you please try to run it on Windows first? is that working?
Thanks

**Comment by surfufu** [comment]
yes, it's working perfectly in widows. I have some news : look like we was using an old version of the NDK and i updated with the r21b as preconized by unreal and look to compile now.  Sorry for this false alerte.

**Comment by wangpingsx** [comment]
> yes, it's working perfectly in widows. I have some news : look like we was using an old version of the NDK and i updated with the r21b as preconized by unreal and look to compile now. Sorry for this false alerte.

Hi Surfufu, so happy to know you made it to work! I am going to close this, but feel free to reach out if need help. thanks
