### ISSUE TITLE
UE5.0.3 TTS not working & no event callbacks

### ISSUE THREAD

**Issue by GameBayoumy** [wit-ai/wit-unreal#57]
Trying to call Speak function, but failed to make connection with the API it seems. When converting TTS, no event callbacks are being called (OnSynthesize)

I've created a Data Asset with Client token. Used a preset from /VoiceSDK/Presets
Calling Speak a second time, the console will log "Warning: ConvertTextToSpeechWithSettings: cannot convert text because a request is already in progress"

Currently using: 
voicesdk-all-in-one-marketplace-ue5_0-47_0_2
UE5.0.3 (Blank template)

![ssPFBcX](https://user-images.githubusercontent.com/1499320/206181714-0bf11ff6-4510-4447-b688-f6c09b026ddd.png)

**Comment by wangpingsx** [comment]
Hi @GameBayoumy, 
How are you? Hope you are having a good week.
I am so happy to know that you are using our plugin.
I will help you with this issue.

1. It will be great if you can share more logs.
2. Could you please try the demo map: /voicesdk-unreal/Content/Demo/Levels/VoiceSDKShapesDemo.umap  if you setup a config with the right client token, you should be able to hear the TTS response("hello TTS") after game started. I just tested; it works as expected.
3. Regarding the second time call.  You will need to add enough delay before the 2nd call.     In later version we will return the audio's duration, so you can make the 2nd call after the 1st audio fully played 
4. the callback -- "OnSynthesizeResponse" works as expected on my side, I cannot see it on your blueprint.

Summary:
Please let's step back a little bit and just make 1 TTS call only. Let's get it to work first, please try the demo map -- VoiceSDKShapesDemo.umap, if it doesn't work for you, please share me more logs.

**Comment by GameBayoumy** [comment]
Hi @wangpingsx, I've been doing great thank you!

For now I try to get started with wit inside UE but still no success. 
My steps are as follows:
1. Create UE blank template
2. Drag voicesdk-unreal inside Plugins folder of project
3. Generate & compiled solution (Development Editor config)
4. Loading VoiceSDKShapesDemo.umap
5. Creating a WitAppConfigurationAsset and setting the Client Access Token from Wit App
6. Changing the BP_TtsSpeaker -> TTS/Configuration to DataAsset with Client Access Token
7. Even tried to Fetch Voices (just in case)
8. Play the map in level editor viewport

No audio, it does log `ConvertTextToSpeechWithSettings: converting text (Hello TTS Demo) with voice (Charlie)`

The rest of the logs when running the game:
LogDebuggerCommands: Repeating last play command: Selected Viewport
LogPlayLevel: PlayLevel: No blueprints needed recompiling
PIE: New page: PIE session: VoiceSDKShapesDemo (8 Dec 2022, 12:12:41)
LogPlayLevel: Creating play world package: /VoiceSDK/Demo/Levels/UEDPIE_0_VoiceSDKShapesDemo
LogPlayLevel: PIE: StaticDuplicateObject took: (0.004404s)
LogPlayLevel: PIE: Created PIE world by copying editor world from /VoiceSDK/Demo/Levels/VoiceSDKShapesDemo.VoiceSDKShapesDemo to /VoiceSDK/Demo/Levels/UEDPIE_0_VoiceSDKShapesDemo.VoiceSDKShapesDemo (0.004499s)
LogSubsystemCollection: Failed to initialize subsystem dependency (WorldPartitionSubsystem)
LogChaos: FPhysicsSolverBase::AsyncDt:-1.000000
LogAIModule: Creating AISystem for world VoiceSDKShapesDemo
LogPlayLevel: PIE: World Init took: (0.000780s)
LogUObjectHash: Compacting FUObjectHashTables data took   0.32ms
LogAudio: Display: Creating Audio Device:                 Id: 12, Scope: Unique, Realtime: True
LogAudioMixer: Display: Audio Mixer Platform Settings:
LogAudioMixer: Display:     Sample Rate:                          48000
LogAudioMixer: Display:     Callback Buffer Frame Size Requested: 1024
LogAudioMixer: Display:     Callback Buffer Frame Size To Use:    1024
LogAudioMixer: Display:     Number of buffers to queue:           2
LogAudioMixer: Display:     Max Channels (voices):                0
LogAudioMixer: Display:     Number of Async Source Workers:       0
LogAudio: Display: AudioDevice MaxSources: 32
LogAudio: Display: Audio Spatialization Plugin: None (built-in).
LogAudio: Display: Audio Reverb Plugin: None (built-in).
LogAudio: Display: Audio Occlusion Plugin: None (built-in).
LogAudioMixer: Display: Initializing audio mixer using platform API: 'XAudio2'
LogAudioMixer: Display: Using Audio Hardware Device Speakers (Realtek(R) Audio)
LogAudioMixer: Display: Initializing Sound Submixes...
LogAudioMixer: Display: Creating Master Submix 'MasterSubmixDefault'
LogAudioMixer: Display: Creating Master Submix 'MasterReverbSubmixDefault'
LogAudioMixer: FMixerPlatformXAudio2::StartAudioStream() called. InstanceID=12
LogAudioMixer: Display: Output buffers initialized: Frames=1024, Channels=8, Samples=8192, InstanceID=12
LogAudioMixer: Display: Starting AudioMixerPlatformInterface::RunInternal(), InstanceID=12
LogAudioMixer: Display: FMixerPlatformXAudio2::SubmitBuffer() called for the first time. InstanceID=12
LogInit: FAudioDevice initialized.
LogAudio: Display: Audio Device (ID: 12) registered with world 'VoiceSDKShapesDemo'.
LogLoad: Game class is 'GameModeBase'
LogWorld: Bringing World /VoiceSDK/Demo/Levels/UEDPIE_0_VoiceSDKShapesDemo.VoiceSDKShapesDemo up for play (max tick rate 60) at 2022.12.08-11.12.41
LogWorld: Bringing up level for play took: 0.000853
LogOnline: OSS: Created online subsystem instance for: :Context_13
LogVoiceEncode: Display: EncoderVersion: libopus unknown
LogOnlineVoice: OSS: StopLocalVoiceProcessing(0) returned 0xFFFFFFFF
LogOnlineVoice: OSS: Stopping networked voice for user: 0
LogVoiceSDK: Display: Init VoiceService: bIsPlatformIntegrationEnabled=false
LogWit: Display: ConvertTextToSpeechWithSettings: converting text (Hello TTS Demo) with voice (Charlie)
LogViewport: Display: Viewport MouseLockMode Changed, LockOnCapture -> DoNotLock
LogViewport: Display: Viewport MouseCaptureMode Changed, CapturePermanently_IncludingInitialMouseDown -> NoCapture
PIE: Server logged in
PIE: Play in editor total start time 0,09 seconds.

I tried calling API to see connectivity issues perhaps with my network, but executing a curl command with the API seems to work just fine at my end. Also, I got it working inside Unity to test it out. My firewall does not block Unreal Engine neither. And debugging UE5 shows that API calls are being received as well

**Comment by wangpingsx** [comment]
Hi @GameBayoumy  Thanks for helping me debugging this issue.

1. I saw it is using "NVIDIA High Definition Audio" as speaker. Is this a real speaker?
2. May I ask you to login into your wit.ai app and check the language you are using? (under: Management->Settings) TTS only works for English for now.  Please try to create a new app with English language and try again.
3. If this doesn't work, let's zip the project and let me try.
Hope this helps.

Thanks

**Comment by wangpingsx** [comment]
Hi @GameBayoumy  Thanks for helping me debugging this issue.

1. I saw it is using "NVIDIA High Definition Audio" as speaker. Is this a real speaker?
2. May I ask you to login into your wit.ai app and check the language your are using? (under: Management->Settings) it only works with English for now.  Please try to create a new app with English language.
3.  if this doesn't work, let's

**Comment by GameBayoumy** [comment]
Sure! I try to find out as well where it could go wrong, my guess for now is the response of the SendRequest.
1. Yes my real speaker is a monitor connected to a headset, it plays audio from UE. Playing a SoundWave inside editor works
2. Language is EN and I tried creating a new app just now, without any success
3. https://we.tl/t-P0ABILVv7F

If it works at your end, probably somewhere in my UE configuration/setup it wont allow connectivity of sending requests to the Wit API

**Comment by GameBayoumy** [comment]
Okay. So I found this interesting.

I managed to send a simple http request using the same code. But here is what I did to replicate the issue to break it.
1. Remove anything related to Wit inside the map
2. Add my own simple httpRequest actor
3. Closing the editor
4. Load the project again
5. Run the editor with the simple httpRequestActor
6. Response works with json content inside as expected
7. Stopping the editor
9. Adding BP_TTsSpeaker with a TTS Speak function request
10. Run the editor
11. Things start to break, even the simple httpRequestActor gets no response at all

Somehow the http request of Wit is related to causing the issue at my end. Like something get's stuck inside the UE editor http request whenever I add something related to Wit. No http request will work at all unless I restart my editor again and my simple httpRequest actor works again, if I were to remove Wit again.

**Comment by wangpingsx** [comment]
Hi @GameBayoumy, How are you?  hope you had a good weekend.
Sorry for my slow reply. I got COVID and fully offline for a couple of days.
I will take a deep look at these logs. Meantime, could you please do me a favor, try my latest code? Just clone our repos into the Plugins folder. (or use my below scripts)

```
cd Plugins
git clone https://github.com/wit-ai/voicesdk-unreal
git clone https://github.com/wit-ai/wit-unreal
```

**Comment by GameBayoumy** [comment]
Hi @wangpingsx, been doing well, thank you! I hope things are going better with your illness.

I've cloned the plugins inside my project and it gives me the same logs as mentioned above.
For now I haven't looked further into the issue.

**Comment by wangpingsx** [comment]
Hi @GameBayoumy , How are you? Hope you had a good Xmas and happy New Year! I some more tests, but couldn't really reproduce this issue.  Are you still facing the same issue?   thanks

**Comment by mszadko** [comment]
I think i'm having same/similar issue. I tried to make couple different aproaches and with all of them I got same issue. I tired to follow this https://www.youtube.com/watch?v=UB4Uzmw8XA8 with no luck. I tried with sample project (one that comes in plugin from marketplace) and one that you need to download from github and then clone repositories into Plugins folder. I always added those 2 lines needed to Engine.ini file. First call of ActivateVoiceInput returns true. It triggers OnStartVoiceInput then OnMinimumWakeTresholdHit then OnStopVoiceInput and OnStopVoiceInputDueToInactivity/Timeout depends on how long I speak. And then no matter how long I wait I don't get any callback from wit.ai. No OnWitResponse or OnEntitiesMatched. Second try to call ActivateVoiceInput returns false with additional log 
LogWit: Display: SendTranscription: sending transcription (make the cube red)
LogWit: Warning: SendTranscription: cannot send transcription because a request is already in progress
or 
LogWit: Display: VoiceCapture - Init: init start - available (1)
LogWit: Display: ActivateVoiceInput: activated voice input
LogVoiceCapture: Warning: Resetting UncompressedAudioBuffer.
LogWit: Display: BeginStreamRequest: starting stream request
LogWit: Display: TickComponent: deactivating voice input - too long since activation (0) - too long since voice input (1)
LogWit: Display: DeactivateVoiceInput: deactivated voice input
LogWit: Warning: ActivateVoiceInput: cannot activate voice input because a request is already in progress

and this is from my app (not sample) where I'm calling print string whenever event is calles on VoiceEvents component on AppVoiceExperience

**Comment by mszadko** [comment]
Also I noticed that after I closed project I cannot delete log file and something is still writing to it
[2023.01.25-14.16.56:388][773]LogHttp: Display: Http module shutting down, but needs to wait on 11 outstanding Http requests:
[2023.01.25-14.16.56:388][773]LogHttp: Display: 	verb=[GET] url=[https://api.wit.ai/message?v=20230104&q=make%20cube%20red] refs=[1] status=Processing
[2023.01.25-14.16.56:388][773]LogHttp: Display: 	verb=[GET] url=[https://api.wit.ai/message?v=20230104&q=make%20the%20cube%20red] refs=[1] status=Processing
[2023.01.25-14.16.56:388][773]LogHttp: Display: 	verb=[POST] url=[https://datarouter.ol.epicgames.com/datarouter/api/v1/public/data?SessionID=&AppID=UEEditor.Rocket.Release&AppVersion=4.27.2-18319896%2B%2B%2BUE4%2BRelease-4.27&UserID=&AppEnvironment=datacollector-binary&UploadType=eteventstream] refs=[1] status=Processing
[2023.01.25-14.16.56:388][773]LogHttp: Display: 	verb=[POST] url=[https://api.wit.ai/speech?v=20230104] refs=[1] status=Processing
[2023.01.25-14.16.56:388][773]LogHttp: Display: 	verb=[POST] url=[https://datarouter.ol.epicgames.com/datarouter/api/v1/public/data?SessionID=&AppID=UEEditor.Rocket.Release&AppVersion=4.27.2-18319896%2B%2B%2BUE4%2BRelease-4.27&UserID=&AppEnvironment=datacollector-binary&UploadType=eteventstream] refs=[1] status=Processing
[2023.01.25-14.16.56:388][773]LogHttp: Display: 	verb=[POST] url=[https://api.wit.ai/speech?v=20230104] refs=[1] status=Processing
[2023.01.25-14.16.56:388][773]LogHttp: Display: 	verb=[POST] url=[https://datarouter.ol.epicgames.com/datarouter/api/v1/public/data?SessionID=AppID=UEEditor.Rocket.Release&AppVersion=4.27.2-18319896%2B%2B%2BUE4%2BRelease-4.27&UserID=&AppEnvironment=datacollector-binary&UploadType=eteventstream] refs=[1] status=Processing
[2023.01.25-14.16.56:388][773]LogHttp: Display: 	verb=[GET] url=[https://api.wit.ai/apps?v=20230104&offset=0&limit=10] refs=[1] status=Processing
[2023.01.25-14.16.56:388][773]LogHttp: Display: 	verb=[POST] url=[https://api.wit.ai/speech?v=20230104] refs=[1] status=Processing
[2023.01.25-14.16.56:388][773]LogHttp: Display: 	verb=[GET] url=[https://api.wit.ai/message?v=20230104&q=make%20the%20cube%20red] refs=[1] status=Processing
[2023.01.25-14.16.56:388][773]LogHttp: Display: 	verb=[POST] url=[https://datarouter.ol.epicgames.com/datarouter/api/v1/public/data?SessionID=&AppID=UEEditor.Rocket.Release&AppVersion=4.27.2-18319896%2B%2B%2BUE4%2BRelease-4.27&UserID=&AppEnvironment=datacollector-binary&UploadType=eteventstream] refs=[1] status=Processing
[2023.01.25-14.16.56:388][773]LogHttp: Display: cleaning up 11 outstanding Http requests.
[2023.01.25-14.16.56:388][773]LogHttp: Display: Sleeping 0.500s to wait for 11 outstanding Http requests.
[2023.01.25-14.16.56:889][773]LogHttp: Display: Sleeping 0.500s to wait for 11 outstanding Http requests.
[2023.01.25-14.16.57:390][773]LogHttp: Display: Sleeping 0.500s to wait for 11 outstanding Http requests.
...

**Comment by GameBayoumy** [comment]
I haven't looked further into it. Also think it is not related to wit plugin, but the HttpRequest like mentioned here: [Not getting any response from wit.ai](https://github.com/wit-ai/voicesdk-unreal/issues/30)
